/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppKontoRouteImport } from './routes/_app/konto'
import { Route as AppOrganisationsanfragenRouteImport } from './routes/_app/organisationsanfragen'
import { Route as AppProfilRouteImport } from './routes/_app/profil'
import { Route as AppSkripteRouteImport } from './routes/_app/skripte'
import { Route as AppUebersichtRouteImport } from './routes/_app/uebersicht'
import { Route as AnfragenIndexRouteImport } from './routes/anfragen/index'
import { Route as AnfragenSplatRouteImport } from './routes/anfragen/$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppAdminBenutzerRouteImport } from './routes/_app/admin/benutzer'
import { Route as AppAdminEmailsRouteImport } from './routes/_app/admin/emails'
import { Route as AppAdminFreigabenRouteImport } from './routes/_app/admin/freigaben'
import { Route as AppAdminKatalogRouteImport } from './routes/_app/admin/katalog'
import { Route as AppAdminProtokollRouteImport } from './routes/_app/admin/protokoll'
import { Route as AppAuftraegeIndexRouteImport } from './routes/_app/auftraege/index'
import { Route as AppAuftraegeRequestIdRouteImport } from './routes/_app/auftraege/$requestId'
import { Route as AppAuftraegeBoardRouteImport } from './routes/_app/auftraege/board'
import { Route as AppAuftraegeNeuRouteImport } from './routes/_app/auftraege/neu'
import { Route as AppEinladungTokenRouteImport } from './routes/_app/einladung.$token'
import { Route as AppOrganisationenOrganisationIdRouteImport } from './routes/_app/organisationen.$organisationId'
import { Route as ApiAuftraegeExportRouteImport } from './routes/api/auftraege/export'
import { Route as ApiDateienIndexRouteImport } from './routes/api/dateien/index'
import { Route as ApiDateienFileIdRouteImport } from './routes/api/dateien/$fileId'
import { Route as ApiRechnungenLexwareRouteImport } from './routes/api/rechnungen/lexware'
import { Route as AppAdminOrganisationenIndexRouteImport } from './routes/_app/admin/organisationen/index'
import { Route as AppAdminOrganisationenOrganisationIdRouteImport } from './routes/_app/admin/organisationen/$organisationId'
import { Route as AppAdminOrganisationenNeuRouteImport } from './routes/_app/admin/organisationen/neu'
import { Route as ApiAdminDatenauskunftUserIdRouteImport } from './routes/api/admin/datenauskunft/$userId'
import { Route as ApiAuthKundenSsoCallbackRouteImport } from './routes/api/auth/kunden-sso/callback'
import { Route as ApiAuthKundenSsoLoginRouteImport } from './routes/api/auth/kunden-sso/login'
import { Route as ApiAuthOidcCallbackRouteImport } from './routes/api/auth/oidc/callback'
import { Route as ApiAuthOidcLoginRouteImport } from './routes/api/auth/oidc/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppKontoRoute = AppKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationsanfragenRoute =
  AppOrganisationsanfragenRouteImport.update({
    id: '/organisationsanfragen',
    path: '/organisationsanfragen',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppSkripteRoute = AppSkripteRouteImport.update({
  id: '/skripte',
  path: '/skripte',
  getParentRoute: () => AppRoute,
} as any)
const AppUebersichtRoute = AppUebersichtRouteImport.update({
  id: '/uebersicht',
  path: '/uebersicht',
  getParentRoute: () => AppRoute,
} as any)
const AnfragenIndexRoute = AnfragenIndexRouteImport.update({
  id: '/anfragen/',
  path: '/anfragen/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnfragenSplatRoute = AnfragenSplatRouteImport.update({
  id: '/anfragen/$',
  path: '/anfragen/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminBenutzerRoute = AppAdminBenutzerRouteImport.update({
  id: '/benutzer',
  path: '/benutzer',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminEmailsRoute = AppAdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminFreigabenRoute = AppAdminFreigabenRouteImport.update({
  id: '/freigaben',
  path: '/freigaben',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminKatalogRoute = AppAdminKatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProtokollRoute = AppAdminProtokollRouteImport.update({
  id: '/protokoll',
  path: '/protokoll',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAuftraegeIndexRoute = AppAuftraegeIndexRouteImport.update({
  id: '/auftraege/',
  path: '/auftraege/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuftraegeRequestIdRoute = AppAuftraegeRequestIdRouteImport.update({
  id: '/auftraege/$requestId',
  path: '/auftraege/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const AppAuftraegeBoardRoute = AppAuftraegeBoardRouteImport.update({
  id: '/auftraege/board',
  path: '/auftraege/board',
  getParentRoute: () => AppRoute,
} as any)
const AppAuftraegeNeuRoute = AppAuftraegeNeuRouteImport.update({
  id: '/auftraege/neu',
  path: '/auftraege/neu',
  getParentRoute: () => AppRoute,
} as any)
const AppEinladungTokenRoute = AppEinladungTokenRouteImport.update({
  id: '/einladung/$token',
  path: '/einladung/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationenOrganisationIdRoute =
  AppOrganisationenOrganisationIdRouteImport.update({
    id: '/organisationen/$organisationId',
    path: '/organisationen/$organisationId',
    getParentRoute: () => AppRoute,
  } as any)
const ApiAuftraegeExportRoute = ApiAuftraegeExportRouteImport.update({
  id: '/api/auftraege/export',
  path: '/api/auftraege/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDateienIndexRoute = ApiDateienIndexRouteImport.update({
  id: '/api/dateien/',
  path: '/api/dateien/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDateienFileIdRoute = ApiDateienFileIdRouteImport.update({
  id: '/api/dateien/$fileId',
  path: '/api/dateien/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRechnungenLexwareRoute = ApiRechnungenLexwareRouteImport.update({
  id: '/api/rechnungen/lexware',
  path: '/api/rechnungen/lexware',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminOrganisationenIndexRoute =
  AppAdminOrganisationenIndexRouteImport.update({
    id: '/organisationen/',
    path: '/organisationen/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminOrganisationenOrganisationIdRoute =
  AppAdminOrganisationenOrganisationIdRouteImport.update({
    id: '/organisationen/$organisationId',
    path: '/organisationen/$organisationId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminOrganisationenNeuRoute =
  AppAdminOrganisationenNeuRouteImport.update({
    id: '/organisationen/neu',
    path: '/organisationen/neu',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const ApiAdminDatenauskunftUserIdRoute =
  ApiAdminDatenauskunftUserIdRouteImport.update({
    id: '/api/admin/datenauskunft/$userId',
    path: '/api/admin/datenauskunft/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthKundenSsoCallbackRoute =
  ApiAuthKundenSsoCallbackRouteImport.update({
    id: '/api/auth/kunden-sso/callback',
    path: '/api/auth/kunden-sso/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthKundenSsoLoginRoute = ApiAuthKundenSsoLoginRouteImport.update({
  id: '/api/auth/kunden-sso/login',
  path: '/api/auth/kunden-sso/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOidcCallbackRoute = ApiAuthOidcCallbackRouteImport.update({
  id: '/api/auth/oidc/callback',
  path: '/api/auth/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOidcLoginRoute = ApiAuthOidcLoginRouteImport.update({
  id: '/api/auth/oidc/login',
  path: '/api/auth/oidc/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/login': typeof LoginRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/konto': typeof AppKontoRoute
  '/organisationsanfragen': typeof AppOrganisationsanfragenRoute
  '/profil': typeof AppProfilRoute
  '/skripte': typeof AppSkripteRoute
  '/uebersicht': typeof AppUebersichtRoute
  '/anfragen/$': typeof AnfragenSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/anfragen/': typeof AnfragenIndexRoute
  '/admin/benutzer': typeof AppAdminBenutzerRoute
  '/admin/emails': typeof AppAdminEmailsRoute
  '/admin/freigaben': typeof AppAdminFreigabenRoute
  '/admin/katalog': typeof AppAdminKatalogRoute
  '/admin/protokoll': typeof AppAdminProtokollRoute
  '/auftraege/$requestId': typeof AppAuftraegeRequestIdRoute
  '/auftraege/board': typeof AppAuftraegeBoardRoute
  '/auftraege/neu': typeof AppAuftraegeNeuRoute
  '/einladung/$token': typeof AppEinladungTokenRoute
  '/organisationen/$organisationId': typeof AppOrganisationenOrganisationIdRoute
  '/api/auftraege/export': typeof ApiAuftraegeExportRoute
  '/api/dateien/$fileId': typeof ApiDateienFileIdRoute
  '/api/rechnungen/lexware': typeof ApiRechnungenLexwareRoute
  '/auftraege/': typeof AppAuftraegeIndexRoute
  '/api/dateien/': typeof ApiDateienIndexRoute
  '/admin/organisationen/$organisationId': typeof AppAdminOrganisationenOrganisationIdRoute
  '/admin/organisationen/neu': typeof AppAdminOrganisationenNeuRoute
  '/api/admin/datenauskunft/$userId': typeof ApiAdminDatenauskunftUserIdRoute
  '/api/auth/kunden-sso/callback': typeof ApiAuthKundenSsoCallbackRoute
  '/api/auth/kunden-sso/login': typeof ApiAuthKundenSsoLoginRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/login': typeof ApiAuthOidcLoginRoute
  '/admin/organisationen/': typeof AppAdminOrganisationenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/login': typeof LoginRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/konto': typeof AppKontoRoute
  '/organisationsanfragen': typeof AppOrganisationsanfragenRoute
  '/profil': typeof AppProfilRoute
  '/skripte': typeof AppSkripteRoute
  '/uebersicht': typeof AppUebersichtRoute
  '/anfragen/$': typeof AnfragenSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/anfragen': typeof AnfragenIndexRoute
  '/admin/benutzer': typeof AppAdminBenutzerRoute
  '/admin/emails': typeof AppAdminEmailsRoute
  '/admin/freigaben': typeof AppAdminFreigabenRoute
  '/admin/katalog': typeof AppAdminKatalogRoute
  '/admin/protokoll': typeof AppAdminProtokollRoute
  '/auftraege/$requestId': typeof AppAuftraegeRequestIdRoute
  '/auftraege/board': typeof AppAuftraegeBoardRoute
  '/auftraege/neu': typeof AppAuftraegeNeuRoute
  '/einladung/$token': typeof AppEinladungTokenRoute
  '/organisationen/$organisationId': typeof AppOrganisationenOrganisationIdRoute
  '/api/auftraege/export': typeof ApiAuftraegeExportRoute
  '/api/dateien/$fileId': typeof ApiDateienFileIdRoute
  '/api/rechnungen/lexware': typeof ApiRechnungenLexwareRoute
  '/auftraege': typeof AppAuftraegeIndexRoute
  '/api/dateien': typeof ApiDateienIndexRoute
  '/admin/organisationen/$organisationId': typeof AppAdminOrganisationenOrganisationIdRoute
  '/admin/organisationen/neu': typeof AppAdminOrganisationenNeuRoute
  '/api/admin/datenauskunft/$userId': typeof ApiAdminDatenauskunftUserIdRoute
  '/api/auth/kunden-sso/callback': typeof ApiAuthKundenSsoCallbackRoute
  '/api/auth/kunden-sso/login': typeof ApiAuthKundenSsoLoginRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/login': typeof ApiAuthOidcLoginRoute
  '/admin/organisationen': typeof AppAdminOrganisationenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/anmelden': typeof AnmeldenRoute
  '/login': typeof LoginRoute
  '/registrieren': typeof RegistrierenRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/konto': typeof AppKontoRoute
  '/_app/organisationsanfragen': typeof AppOrganisationsanfragenRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/skripte': typeof AppSkripteRoute
  '/_app/uebersicht': typeof AppUebersichtRoute
  '/anfragen/$': typeof AnfragenSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/anfragen/': typeof AnfragenIndexRoute
  '/_app/admin/benutzer': typeof AppAdminBenutzerRoute
  '/_app/admin/emails': typeof AppAdminEmailsRoute
  '/_app/admin/freigaben': typeof AppAdminFreigabenRoute
  '/_app/admin/katalog': typeof AppAdminKatalogRoute
  '/_app/admin/protokoll': typeof AppAdminProtokollRoute
  '/_app/auftraege/$requestId': typeof AppAuftraegeRequestIdRoute
  '/_app/auftraege/board': typeof AppAuftraegeBoardRoute
  '/_app/auftraege/neu': typeof AppAuftraegeNeuRoute
  '/_app/einladung/$token': typeof AppEinladungTokenRoute
  '/_app/organisationen/$organisationId': typeof AppOrganisationenOrganisationIdRoute
  '/api/auftraege/export': typeof ApiAuftraegeExportRoute
  '/api/dateien/$fileId': typeof ApiDateienFileIdRoute
  '/api/rechnungen/lexware': typeof ApiRechnungenLexwareRoute
  '/_app/auftraege/': typeof AppAuftraegeIndexRoute
  '/api/dateien/': typeof ApiDateienIndexRoute
  '/_app/admin/organisationen/$organisationId': typeof AppAdminOrganisationenOrganisationIdRoute
  '/_app/admin/organisationen/neu': typeof AppAdminOrganisationenNeuRoute
  '/api/admin/datenauskunft/$userId': typeof ApiAdminDatenauskunftUserIdRoute
  '/api/auth/kunden-sso/callback': typeof ApiAuthKundenSsoCallbackRoute
  '/api/auth/kunden-sso/login': typeof ApiAuthKundenSsoLoginRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/login': typeof ApiAuthOidcLoginRoute
  '/_app/admin/organisationen/': typeof AppAdminOrganisationenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/login'
    | '/registrieren'
    | '/admin'
    | '/konto'
    | '/organisationsanfragen'
    | '/profil'
    | '/skripte'
    | '/uebersicht'
    | '/anfragen/$'
    | '/api/health'
    | '/anfragen/'
    | '/admin/benutzer'
    | '/admin/emails'
    | '/admin/freigaben'
    | '/admin/katalog'
    | '/admin/protokoll'
    | '/auftraege/$requestId'
    | '/auftraege/board'
    | '/auftraege/neu'
    | '/einladung/$token'
    | '/organisationen/$organisationId'
    | '/api/auftraege/export'
    | '/api/dateien/$fileId'
    | '/api/rechnungen/lexware'
    | '/auftraege/'
    | '/api/dateien/'
    | '/admin/organisationen/$organisationId'
    | '/admin/organisationen/neu'
    | '/api/admin/datenauskunft/$userId'
    | '/api/auth/kunden-sso/callback'
    | '/api/auth/kunden-sso/login'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/login'
    | '/admin/organisationen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/login'
    | '/registrieren'
    | '/admin'
    | '/konto'
    | '/organisationsanfragen'
    | '/profil'
    | '/skripte'
    | '/uebersicht'
    | '/anfragen/$'
    | '/api/health'
    | '/anfragen'
    | '/admin/benutzer'
    | '/admin/emails'
    | '/admin/freigaben'
    | '/admin/katalog'
    | '/admin/protokoll'
    | '/auftraege/$requestId'
    | '/auftraege/board'
    | '/auftraege/neu'
    | '/einladung/$token'
    | '/organisationen/$organisationId'
    | '/api/auftraege/export'
    | '/api/dateien/$fileId'
    | '/api/rechnungen/lexware'
    | '/auftraege'
    | '/api/dateien'
    | '/admin/organisationen/$organisationId'
    | '/admin/organisationen/neu'
    | '/api/admin/datenauskunft/$userId'
    | '/api/auth/kunden-sso/callback'
    | '/api/auth/kunden-sso/login'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/login'
    | '/admin/organisationen'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/anmelden'
    | '/login'
    | '/registrieren'
    | '/_app/admin'
    | '/_app/konto'
    | '/_app/organisationsanfragen'
    | '/_app/profil'
    | '/_app/skripte'
    | '/_app/uebersicht'
    | '/anfragen/$'
    | '/api/health'
    | '/anfragen/'
    | '/_app/admin/benutzer'
    | '/_app/admin/emails'
    | '/_app/admin/freigaben'
    | '/_app/admin/katalog'
    | '/_app/admin/protokoll'
    | '/_app/auftraege/$requestId'
    | '/_app/auftraege/board'
    | '/_app/auftraege/neu'
    | '/_app/einladung/$token'
    | '/_app/organisationen/$organisationId'
    | '/api/auftraege/export'
    | '/api/dateien/$fileId'
    | '/api/rechnungen/lexware'
    | '/_app/auftraege/'
    | '/api/dateien/'
    | '/_app/admin/organisationen/$organisationId'
    | '/_app/admin/organisationen/neu'
    | '/api/admin/datenauskunft/$userId'
    | '/api/auth/kunden-sso/callback'
    | '/api/auth/kunden-sso/login'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/login'
    | '/_app/admin/organisationen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AnmeldenRoute: typeof AnmeldenRoute
  LoginRoute: typeof LoginRoute
  RegistrierenRoute: typeof RegistrierenRoute
  AnfragenSplatRoute: typeof AnfragenSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AnfragenIndexRoute: typeof AnfragenIndexRoute
  ApiAuftraegeExportRoute: typeof ApiAuftraegeExportRoute
  ApiDateienFileIdRoute: typeof ApiDateienFileIdRoute
  ApiRechnungenLexwareRoute: typeof ApiRechnungenLexwareRoute
  ApiDateienIndexRoute: typeof ApiDateienIndexRoute
  ApiAdminDatenauskunftUserIdRoute: typeof ApiAdminDatenauskunftUserIdRoute
  ApiAuthKundenSsoCallbackRoute: typeof ApiAuthKundenSsoCallbackRoute
  ApiAuthKundenSsoLoginRoute: typeof ApiAuthKundenSsoLoginRoute
  ApiAuthOidcCallbackRoute: typeof ApiAuthOidcCallbackRoute
  ApiAuthOidcLoginRoute: typeof ApiAuthOidcLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/konto': {
      id: '/_app/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AppKontoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organisationsanfragen': {
      id: '/_app/organisationsanfragen'
      path: '/organisationsanfragen'
      fullPath: '/organisationsanfragen'
      preLoaderRoute: typeof AppOrganisationsanfragenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skripte': {
      id: '/_app/skripte'
      path: '/skripte'
      fullPath: '/skripte'
      preLoaderRoute: typeof AppSkripteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uebersicht': {
      id: '/_app/uebersicht'
      path: '/uebersicht'
      fullPath: '/uebersicht'
      preLoaderRoute: typeof AppUebersichtRouteImport
      parentRoute: typeof AppRoute
    }
    '/anfragen/': {
      id: '/anfragen/'
      path: '/anfragen'
      fullPath: '/anfragen/'
      preLoaderRoute: typeof AnfragenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anfragen/$': {
      id: '/anfragen/$'
      path: '/anfragen/$'
      fullPath: '/anfragen/$'
      preLoaderRoute: typeof AnfragenSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/benutzer': {
      id: '/_app/admin/benutzer'
      path: '/benutzer'
      fullPath: '/admin/benutzer'
      preLoaderRoute: typeof AppAdminBenutzerRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/emails': {
      id: '/_app/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AppAdminEmailsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/freigaben': {
      id: '/_app/admin/freigaben'
      path: '/freigaben'
      fullPath: '/admin/freigaben'
      preLoaderRoute: typeof AppAdminFreigabenRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/katalog': {
      id: '/_app/admin/katalog'
      path: '/katalog'
      fullPath: '/admin/katalog'
      preLoaderRoute: typeof AppAdminKatalogRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/protokoll': {
      id: '/_app/admin/protokoll'
      path: '/protokoll'
      fullPath: '/admin/protokoll'
      preLoaderRoute: typeof AppAdminProtokollRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/auftraege/': {
      id: '/_app/auftraege/'
      path: '/auftraege'
      fullPath: '/auftraege/'
      preLoaderRoute: typeof AppAuftraegeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auftraege/$requestId': {
      id: '/_app/auftraege/$requestId'
      path: '/auftraege/$requestId'
      fullPath: '/auftraege/$requestId'
      preLoaderRoute: typeof AppAuftraegeRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auftraege/board': {
      id: '/_app/auftraege/board'
      path: '/auftraege/board'
      fullPath: '/auftraege/board'
      preLoaderRoute: typeof AppAuftraegeBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auftraege/neu': {
      id: '/_app/auftraege/neu'
      path: '/auftraege/neu'
      fullPath: '/auftraege/neu'
      preLoaderRoute: typeof AppAuftraegeNeuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/einladung/$token': {
      id: '/_app/einladung/$token'
      path: '/einladung/$token'
      fullPath: '/einladung/$token'
      preLoaderRoute: typeof AppEinladungTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organisationen/$organisationId': {
      id: '/_app/organisationen/$organisationId'
      path: '/organisationen/$organisationId'
      fullPath: '/organisationen/$organisationId'
      preLoaderRoute: typeof AppOrganisationenOrganisationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auftraege/export': {
      id: '/api/auftraege/export'
      path: '/api/auftraege/export'
      fullPath: '/api/auftraege/export'
      preLoaderRoute: typeof ApiAuftraegeExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dateien/': {
      id: '/api/dateien/'
      path: '/api/dateien'
      fullPath: '/api/dateien/'
      preLoaderRoute: typeof ApiDateienIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dateien/$fileId': {
      id: '/api/dateien/$fileId'
      path: '/api/dateien/$fileId'
      fullPath: '/api/dateien/$fileId'
      preLoaderRoute: typeof ApiDateienFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rechnungen/lexware': {
      id: '/api/rechnungen/lexware'
      path: '/api/rechnungen/lexware'
      fullPath: '/api/rechnungen/lexware'
      preLoaderRoute: typeof ApiRechnungenLexwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/organisationen/': {
      id: '/_app/admin/organisationen/'
      path: '/organisationen'
      fullPath: '/admin/organisationen/'
      preLoaderRoute: typeof AppAdminOrganisationenIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/organisationen/$organisationId': {
      id: '/_app/admin/organisationen/$organisationId'
      path: '/organisationen/$organisationId'
      fullPath: '/admin/organisationen/$organisationId'
      preLoaderRoute: typeof AppAdminOrganisationenOrganisationIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/organisationen/neu': {
      id: '/_app/admin/organisationen/neu'
      path: '/organisationen/neu'
      fullPath: '/admin/organisationen/neu'
      preLoaderRoute: typeof AppAdminOrganisationenNeuRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/api/admin/datenauskunft/$userId': {
      id: '/api/admin/datenauskunft/$userId'
      path: '/api/admin/datenauskunft/$userId'
      fullPath: '/api/admin/datenauskunft/$userId'
      preLoaderRoute: typeof ApiAdminDatenauskunftUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/kunden-sso/callback': {
      id: '/api/auth/kunden-sso/callback'
      path: '/api/auth/kunden-sso/callback'
      fullPath: '/api/auth/kunden-sso/callback'
      preLoaderRoute: typeof ApiAuthKundenSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/kunden-sso/login': {
      id: '/api/auth/kunden-sso/login'
      path: '/api/auth/kunden-sso/login'
      fullPath: '/api/auth/kunden-sso/login'
      preLoaderRoute: typeof ApiAuthKundenSsoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/oidc/callback': {
      id: '/api/auth/oidc/callback'
      path: '/api/auth/oidc/callback'
      fullPath: '/api/auth/oidc/callback'
      preLoaderRoute: typeof ApiAuthOidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/oidc/login': {
      id: '/api/auth/oidc/login'
      path: '/api/auth/oidc/login'
      fullPath: '/api/auth/oidc/login'
      preLoaderRoute: typeof ApiAuthOidcLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminBenutzerRoute: typeof AppAdminBenutzerRoute
  AppAdminEmailsRoute: typeof AppAdminEmailsRoute
  AppAdminFreigabenRoute: typeof AppAdminFreigabenRoute
  AppAdminKatalogRoute: typeof AppAdminKatalogRoute
  AppAdminProtokollRoute: typeof AppAdminProtokollRoute
  AppAdminOrganisationenOrganisationIdRoute: typeof AppAdminOrganisationenOrganisationIdRoute
  AppAdminOrganisationenNeuRoute: typeof AppAdminOrganisationenNeuRoute
  AppAdminOrganisationenIndexRoute: typeof AppAdminOrganisationenIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminBenutzerRoute: AppAdminBenutzerRoute,
  AppAdminEmailsRoute: AppAdminEmailsRoute,
  AppAdminFreigabenRoute: AppAdminFreigabenRoute,
  AppAdminKatalogRoute: AppAdminKatalogRoute,
  AppAdminProtokollRoute: AppAdminProtokollRoute,
  AppAdminOrganisationenOrganisationIdRoute:
    AppAdminOrganisationenOrganisationIdRoute,
  AppAdminOrganisationenNeuRoute: AppAdminOrganisationenNeuRoute,
  AppAdminOrganisationenIndexRoute: AppAdminOrganisationenIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppKontoRoute: typeof AppKontoRoute
  AppOrganisationsanfragenRoute: typeof AppOrganisationsanfragenRoute
  AppProfilRoute: typeof AppProfilRoute
  AppSkripteRoute: typeof AppSkripteRoute
  AppUebersichtRoute: typeof AppUebersichtRoute
  AppAuftraegeRequestIdRoute: typeof AppAuftraegeRequestIdRoute
  AppAuftraegeBoardRoute: typeof AppAuftraegeBoardRoute
  AppAuftraegeNeuRoute: typeof AppAuftraegeNeuRoute
  AppEinladungTokenRoute: typeof AppEinladungTokenRoute
  AppOrganisationenOrganisationIdRoute: typeof AppOrganisationenOrganisationIdRoute
  AppAuftraegeIndexRoute: typeof AppAuftraegeIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppKontoRoute: AppKontoRoute,
  AppOrganisationsanfragenRoute: AppOrganisationsanfragenRoute,
  AppProfilRoute: AppProfilRoute,
  AppSkripteRoute: AppSkripteRoute,
  AppUebersichtRoute: AppUebersichtRoute,
  AppAuftraegeRequestIdRoute: AppAuftraegeRequestIdRoute,
  AppAuftraegeBoardRoute: AppAuftraegeBoardRoute,
  AppAuftraegeNeuRoute: AppAuftraegeNeuRoute,
  AppEinladungTokenRoute: AppEinladungTokenRoute,
  AppOrganisationenOrganisationIdRoute: AppOrganisationenOrganisationIdRoute,
  AppAuftraegeIndexRoute: AppAuftraegeIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AnmeldenRoute: AnmeldenRoute,
  LoginRoute: LoginRoute,
  RegistrierenRoute: RegistrierenRoute,
  AnfragenSplatRoute: AnfragenSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  AnfragenIndexRoute: AnfragenIndexRoute,
  ApiAuftraegeExportRoute: ApiAuftraegeExportRoute,
  ApiDateienFileIdRoute: ApiDateienFileIdRoute,
  ApiRechnungenLexwareRoute: ApiRechnungenLexwareRoute,
  ApiDateienIndexRoute: ApiDateienIndexRoute,
  ApiAdminDatenauskunftUserIdRoute: ApiAdminDatenauskunftUserIdRoute,
  ApiAuthKundenSsoCallbackRoute: ApiAuthKundenSsoCallbackRoute,
  ApiAuthKundenSsoLoginRoute: ApiAuthKundenSsoLoginRoute,
  ApiAuthOidcCallbackRoute: ApiAuthOidcCallbackRoute,
  ApiAuthOidcLoginRoute: ApiAuthOidcLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
