/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppKontoRouteImport } from './routes/_app/konto'
import { Route as AppProfilRouteImport } from './routes/_app/profil'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppAdminBenutzerRouteImport } from './routes/_app/admin/benutzer'
import { Route as AppAdminFreigabenRouteImport } from './routes/_app/admin/freigaben'
import { Route as AppAdminKatalogRouteImport } from './routes/_app/admin/katalog'
import { Route as AppAnfragenIndexRouteImport } from './routes/_app/anfragen/index'
import { Route as AppAnfragenRequestIdRouteImport } from './routes/_app/anfragen/$requestId'
import { Route as AppAnfragenNeuRouteImport } from './routes/_app/anfragen/neu'
import { Route as AppAdminOrganisationenIndexRouteImport } from './routes/_app/admin/organisationen/index'
import { Route as AppAdminOrganisationenOrganisationIdRouteImport } from './routes/_app/admin/organisationen/$organisationId'
import { Route as AppAdminOrganisationenNeuRouteImport } from './routes/_app/admin/organisationen/neu'
import { Route as ApiAuthOidcCallbackRouteImport } from './routes/api/auth/oidc/callback'
import { Route as ApiAuthOidcLoginRouteImport } from './routes/api/auth/oidc/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppKontoRoute = AppKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminBenutzerRoute = AppAdminBenutzerRouteImport.update({
  id: '/benutzer',
  path: '/benutzer',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminFreigabenRoute = AppAdminFreigabenRouteImport.update({
  id: '/freigaben',
  path: '/freigaben',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminKatalogRoute = AppAdminKatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAnfragenIndexRoute = AppAnfragenIndexRouteImport.update({
  id: '/anfragen/',
  path: '/anfragen/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnfragenRequestIdRoute = AppAnfragenRequestIdRouteImport.update({
  id: '/anfragen/$requestId',
  path: '/anfragen/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const AppAnfragenNeuRoute = AppAnfragenNeuRouteImport.update({
  id: '/anfragen/neu',
  path: '/anfragen/neu',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrganisationenIndexRoute =
  AppAdminOrganisationenIndexRouteImport.update({
    id: '/organisationen/',
    path: '/organisationen/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminOrganisationenOrganisationIdRoute =
  AppAdminOrganisationenOrganisationIdRouteImport.update({
    id: '/organisationen/$organisationId',
    path: '/organisationen/$organisationId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminOrganisationenNeuRoute =
  AppAdminOrganisationenNeuRouteImport.update({
    id: '/organisationen/neu',
    path: '/organisationen/neu',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const ApiAuthOidcCallbackRoute = ApiAuthOidcCallbackRouteImport.update({
  id: '/api/auth/oidc/callback',
  path: '/api/auth/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOidcLoginRoute = ApiAuthOidcLoginRouteImport.update({
  id: '/api/auth/oidc/login',
  path: '/api/auth/oidc/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/login': typeof LoginRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/konto': typeof AppKontoRoute
  '/profil': typeof AppProfilRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/benutzer': typeof AppAdminBenutzerRoute
  '/admin/freigaben': typeof AppAdminFreigabenRoute
  '/admin/katalog': typeof AppAdminKatalogRoute
  '/anfragen/$requestId': typeof AppAnfragenRequestIdRoute
  '/anfragen/neu': typeof AppAnfragenNeuRoute
  '/anfragen/': typeof AppAnfragenIndexRoute
  '/admin/organisationen/$organisationId': typeof AppAdminOrganisationenOrganisationIdRoute
  '/admin/organisationen/neu': typeof AppAdminOrganisationenNeuRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/login': typeof ApiAuthOidcLoginRoute
  '/admin/organisationen/': typeof AppAdminOrganisationenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/login': typeof LoginRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/konto': typeof AppKontoRoute
  '/profil': typeof AppProfilRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/benutzer': typeof AppAdminBenutzerRoute
  '/admin/freigaben': typeof AppAdminFreigabenRoute
  '/admin/katalog': typeof AppAdminKatalogRoute
  '/anfragen/$requestId': typeof AppAnfragenRequestIdRoute
  '/anfragen/neu': typeof AppAnfragenNeuRoute
  '/anfragen': typeof AppAnfragenIndexRoute
  '/admin/organisationen/$organisationId': typeof AppAdminOrganisationenOrganisationIdRoute
  '/admin/organisationen/neu': typeof AppAdminOrganisationenNeuRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/login': typeof ApiAuthOidcLoginRoute
  '/admin/organisationen': typeof AppAdminOrganisationenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/anmelden': typeof AnmeldenRoute
  '/login': typeof LoginRoute
  '/registrieren': typeof RegistrierenRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/konto': typeof AppKontoRoute
  '/_app/profil': typeof AppProfilRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/admin/benutzer': typeof AppAdminBenutzerRoute
  '/_app/admin/freigaben': typeof AppAdminFreigabenRoute
  '/_app/admin/katalog': typeof AppAdminKatalogRoute
  '/_app/anfragen/$requestId': typeof AppAnfragenRequestIdRoute
  '/_app/anfragen/neu': typeof AppAnfragenNeuRoute
  '/_app/anfragen/': typeof AppAnfragenIndexRoute
  '/_app/admin/organisationen/$organisationId': typeof AppAdminOrganisationenOrganisationIdRoute
  '/_app/admin/organisationen/neu': typeof AppAdminOrganisationenNeuRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/login': typeof ApiAuthOidcLoginRoute
  '/_app/admin/organisationen/': typeof AppAdminOrganisationenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/login'
    | '/registrieren'
    | '/admin'
    | '/konto'
    | '/profil'
    | '/api/health'
    | '/admin/benutzer'
    | '/admin/freigaben'
    | '/admin/katalog'
    | '/anfragen/$requestId'
    | '/anfragen/neu'
    | '/anfragen/'
    | '/admin/organisationen/$organisationId'
    | '/admin/organisationen/neu'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/login'
    | '/admin/organisationen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/login'
    | '/registrieren'
    | '/admin'
    | '/konto'
    | '/profil'
    | '/api/health'
    | '/admin/benutzer'
    | '/admin/freigaben'
    | '/admin/katalog'
    | '/anfragen/$requestId'
    | '/anfragen/neu'
    | '/anfragen'
    | '/admin/organisationen/$organisationId'
    | '/admin/organisationen/neu'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/login'
    | '/admin/organisationen'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/anmelden'
    | '/login'
    | '/registrieren'
    | '/_app/admin'
    | '/_app/konto'
    | '/_app/profil'
    | '/api/health'
    | '/_app/admin/benutzer'
    | '/_app/admin/freigaben'
    | '/_app/admin/katalog'
    | '/_app/anfragen/$requestId'
    | '/_app/anfragen/neu'
    | '/_app/anfragen/'
    | '/_app/admin/organisationen/$organisationId'
    | '/_app/admin/organisationen/neu'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/login'
    | '/_app/admin/organisationen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AnmeldenRoute: typeof AnmeldenRoute
  LoginRoute: typeof LoginRoute
  RegistrierenRoute: typeof RegistrierenRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthOidcCallbackRoute: typeof ApiAuthOidcCallbackRoute
  ApiAuthOidcLoginRoute: typeof ApiAuthOidcLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/konto': {
      id: '/_app/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AppKontoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/benutzer': {
      id: '/_app/admin/benutzer'
      path: '/benutzer'
      fullPath: '/admin/benutzer'
      preLoaderRoute: typeof AppAdminBenutzerRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/freigaben': {
      id: '/_app/admin/freigaben'
      path: '/freigaben'
      fullPath: '/admin/freigaben'
      preLoaderRoute: typeof AppAdminFreigabenRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/katalog': {
      id: '/_app/admin/katalog'
      path: '/katalog'
      fullPath: '/admin/katalog'
      preLoaderRoute: typeof AppAdminKatalogRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/anfragen/': {
      id: '/_app/anfragen/'
      path: '/anfragen'
      fullPath: '/anfragen/'
      preLoaderRoute: typeof AppAnfragenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anfragen/$requestId': {
      id: '/_app/anfragen/$requestId'
      path: '/anfragen/$requestId'
      fullPath: '/anfragen/$requestId'
      preLoaderRoute: typeof AppAnfragenRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anfragen/neu': {
      id: '/_app/anfragen/neu'
      path: '/anfragen/neu'
      fullPath: '/anfragen/neu'
      preLoaderRoute: typeof AppAnfragenNeuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/organisationen/': {
      id: '/_app/admin/organisationen/'
      path: '/organisationen'
      fullPath: '/admin/organisationen/'
      preLoaderRoute: typeof AppAdminOrganisationenIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/organisationen/$organisationId': {
      id: '/_app/admin/organisationen/$organisationId'
      path: '/organisationen/$organisationId'
      fullPath: '/admin/organisationen/$organisationId'
      preLoaderRoute: typeof AppAdminOrganisationenOrganisationIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/organisationen/neu': {
      id: '/_app/admin/organisationen/neu'
      path: '/organisationen/neu'
      fullPath: '/admin/organisationen/neu'
      preLoaderRoute: typeof AppAdminOrganisationenNeuRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/api/auth/oidc/callback': {
      id: '/api/auth/oidc/callback'
      path: '/api/auth/oidc/callback'
      fullPath: '/api/auth/oidc/callback'
      preLoaderRoute: typeof ApiAuthOidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/oidc/login': {
      id: '/api/auth/oidc/login'
      path: '/api/auth/oidc/login'
      fullPath: '/api/auth/oidc/login'
      preLoaderRoute: typeof ApiAuthOidcLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminBenutzerRoute: typeof AppAdminBenutzerRoute
  AppAdminFreigabenRoute: typeof AppAdminFreigabenRoute
  AppAdminKatalogRoute: typeof AppAdminKatalogRoute
  AppAdminOrganisationenOrganisationIdRoute: typeof AppAdminOrganisationenOrganisationIdRoute
  AppAdminOrganisationenNeuRoute: typeof AppAdminOrganisationenNeuRoute
  AppAdminOrganisationenIndexRoute: typeof AppAdminOrganisationenIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminBenutzerRoute: AppAdminBenutzerRoute,
  AppAdminFreigabenRoute: AppAdminFreigabenRoute,
  AppAdminKatalogRoute: AppAdminKatalogRoute,
  AppAdminOrganisationenOrganisationIdRoute:
    AppAdminOrganisationenOrganisationIdRoute,
  AppAdminOrganisationenNeuRoute: AppAdminOrganisationenNeuRoute,
  AppAdminOrganisationenIndexRoute: AppAdminOrganisationenIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppKontoRoute: typeof AppKontoRoute
  AppProfilRoute: typeof AppProfilRoute
  AppAnfragenRequestIdRoute: typeof AppAnfragenRequestIdRoute
  AppAnfragenNeuRoute: typeof AppAnfragenNeuRoute
  AppAnfragenIndexRoute: typeof AppAnfragenIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppKontoRoute: AppKontoRoute,
  AppProfilRoute: AppProfilRoute,
  AppAnfragenRequestIdRoute: AppAnfragenRequestIdRoute,
  AppAnfragenNeuRoute: AppAnfragenNeuRoute,
  AppAnfragenIndexRoute: AppAnfragenIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AnmeldenRoute: AnmeldenRoute,
  LoginRoute: LoginRoute,
  RegistrierenRoute: RegistrierenRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthOidcCallbackRoute: ApiAuthOidcCallbackRoute,
  ApiAuthOidcLoginRoute: ApiAuthOidcLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
