/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppKontoRouteImport } from './routes/_app/konto'
import { Route as AppProfilRouteImport } from './routes/_app/profil'
import { Route as AnfragenIndexRouteImport } from './routes/anfragen/index'
import { Route as AnfragenSplatRouteImport } from './routes/anfragen/$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppAdminBenutzerRouteImport } from './routes/_app/admin/benutzer'
import { Route as AppAdminFreigabenRouteImport } from './routes/_app/admin/freigaben'
import { Route as AppAdminKatalogRouteImport } from './routes/_app/admin/katalog'
import { Route as AppAdminProtokollRouteImport } from './routes/_app/admin/protokoll'
import { Route as AppAuftraegeIndexRouteImport } from './routes/_app/auftraege/index'
import { Route as AppAuftraegeRequestIdRouteImport } from './routes/_app/auftraege/$requestId'
import { Route as AppAuftraegeNeuRouteImport } from './routes/_app/auftraege/neu'
import { Route as ApiDateienIndexRouteImport } from './routes/api/dateien/index'
import { Route as ApiDateienFileIdRouteImport } from './routes/api/dateien/$fileId'
import { Route as AppAdminOrganisationenIndexRouteImport } from './routes/_app/admin/organisationen/index'
import { Route as AppAdminOrganisationenOrganisationIdRouteImport } from './routes/_app/admin/organisationen/$organisationId'
import { Route as AppAdminOrganisationenNeuRouteImport } from './routes/_app/admin/organisationen/neu'
import { Route as ApiAuthOidcCallbackRouteImport } from './routes/api/auth/oidc/callback'
import { Route as ApiAuthOidcLoginRouteImport } from './routes/api/auth/oidc/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppKontoRoute = AppKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AnfragenIndexRoute = AnfragenIndexRouteImport.update({
  id: '/anfragen/',
  path: '/anfragen/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnfragenSplatRoute = AnfragenSplatRouteImport.update({
  id: '/anfragen/$',
  path: '/anfragen/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminBenutzerRoute = AppAdminBenutzerRouteImport.update({
  id: '/benutzer',
  path: '/benutzer',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminFreigabenRoute = AppAdminFreigabenRouteImport.update({
  id: '/freigaben',
  path: '/freigaben',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminKatalogRoute = AppAdminKatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProtokollRoute = AppAdminProtokollRouteImport.update({
  id: '/protokoll',
  path: '/protokoll',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAuftraegeIndexRoute = AppAuftraegeIndexRouteImport.update({
  id: '/auftraege/',
  path: '/auftraege/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuftraegeRequestIdRoute = AppAuftraegeRequestIdRouteImport.update({
  id: '/auftraege/$requestId',
  path: '/auftraege/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const AppAuftraegeNeuRoute = AppAuftraegeNeuRouteImport.update({
  id: '/auftraege/neu',
  path: '/auftraege/neu',
  getParentRoute: () => AppRoute,
} as any)
const ApiDateienIndexRoute = ApiDateienIndexRouteImport.update({
  id: '/api/dateien/',
  path: '/api/dateien/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDateienFileIdRoute = ApiDateienFileIdRouteImport.update({
  id: '/api/dateien/$fileId',
  path: '/api/dateien/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminOrganisationenIndexRoute =
  AppAdminOrganisationenIndexRouteImport.update({
    id: '/organisationen/',
    path: '/organisationen/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminOrganisationenOrganisationIdRoute =
  AppAdminOrganisationenOrganisationIdRouteImport.update({
    id: '/organisationen/$organisationId',
    path: '/organisationen/$organisationId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminOrganisationenNeuRoute =
  AppAdminOrganisationenNeuRouteImport.update({
    id: '/organisationen/neu',
    path: '/organisationen/neu',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const ApiAuthOidcCallbackRoute = ApiAuthOidcCallbackRouteImport.update({
  id: '/api/auth/oidc/callback',
  path: '/api/auth/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOidcLoginRoute = ApiAuthOidcLoginRouteImport.update({
  id: '/api/auth/oidc/login',
  path: '/api/auth/oidc/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/login': typeof LoginRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/konto': typeof AppKontoRoute
  '/profil': typeof AppProfilRoute
  '/anfragen/$': typeof AnfragenSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/anfragen/': typeof AnfragenIndexRoute
  '/admin/benutzer': typeof AppAdminBenutzerRoute
  '/admin/freigaben': typeof AppAdminFreigabenRoute
  '/admin/katalog': typeof AppAdminKatalogRoute
  '/admin/protokoll': typeof AppAdminProtokollRoute
  '/auftraege/$requestId': typeof AppAuftraegeRequestIdRoute
  '/auftraege/neu': typeof AppAuftraegeNeuRoute
  '/api/dateien/$fileId': typeof ApiDateienFileIdRoute
  '/auftraege/': typeof AppAuftraegeIndexRoute
  '/api/dateien/': typeof ApiDateienIndexRoute
  '/admin/organisationen/$organisationId': typeof AppAdminOrganisationenOrganisationIdRoute
  '/admin/organisationen/neu': typeof AppAdminOrganisationenNeuRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/login': typeof ApiAuthOidcLoginRoute
  '/admin/organisationen/': typeof AppAdminOrganisationenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/login': typeof LoginRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/konto': typeof AppKontoRoute
  '/profil': typeof AppProfilRoute
  '/anfragen/$': typeof AnfragenSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/anfragen': typeof AnfragenIndexRoute
  '/admin/benutzer': typeof AppAdminBenutzerRoute
  '/admin/freigaben': typeof AppAdminFreigabenRoute
  '/admin/katalog': typeof AppAdminKatalogRoute
  '/admin/protokoll': typeof AppAdminProtokollRoute
  '/auftraege/$requestId': typeof AppAuftraegeRequestIdRoute
  '/auftraege/neu': typeof AppAuftraegeNeuRoute
  '/api/dateien/$fileId': typeof ApiDateienFileIdRoute
  '/auftraege': typeof AppAuftraegeIndexRoute
  '/api/dateien': typeof ApiDateienIndexRoute
  '/admin/organisationen/$organisationId': typeof AppAdminOrganisationenOrganisationIdRoute
  '/admin/organisationen/neu': typeof AppAdminOrganisationenNeuRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/login': typeof ApiAuthOidcLoginRoute
  '/admin/organisationen': typeof AppAdminOrganisationenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/anmelden': typeof AnmeldenRoute
  '/login': typeof LoginRoute
  '/registrieren': typeof RegistrierenRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/konto': typeof AppKontoRoute
  '/_app/profil': typeof AppProfilRoute
  '/anfragen/$': typeof AnfragenSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/anfragen/': typeof AnfragenIndexRoute
  '/_app/admin/benutzer': typeof AppAdminBenutzerRoute
  '/_app/admin/freigaben': typeof AppAdminFreigabenRoute
  '/_app/admin/katalog': typeof AppAdminKatalogRoute
  '/_app/admin/protokoll': typeof AppAdminProtokollRoute
  '/_app/auftraege/$requestId': typeof AppAuftraegeRequestIdRoute
  '/_app/auftraege/neu': typeof AppAuftraegeNeuRoute
  '/api/dateien/$fileId': typeof ApiDateienFileIdRoute
  '/_app/auftraege/': typeof AppAuftraegeIndexRoute
  '/api/dateien/': typeof ApiDateienIndexRoute
  '/_app/admin/organisationen/$organisationId': typeof AppAdminOrganisationenOrganisationIdRoute
  '/_app/admin/organisationen/neu': typeof AppAdminOrganisationenNeuRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/login': typeof ApiAuthOidcLoginRoute
  '/_app/admin/organisationen/': typeof AppAdminOrganisationenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/login'
    | '/registrieren'
    | '/admin'
    | '/konto'
    | '/profil'
    | '/anfragen/$'
    | '/api/health'
    | '/anfragen/'
    | '/admin/benutzer'
    | '/admin/freigaben'
    | '/admin/katalog'
    | '/admin/protokoll'
    | '/auftraege/$requestId'
    | '/auftraege/neu'
    | '/api/dateien/$fileId'
    | '/auftraege/'
    | '/api/dateien/'
    | '/admin/organisationen/$organisationId'
    | '/admin/organisationen/neu'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/login'
    | '/admin/organisationen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/login'
    | '/registrieren'
    | '/admin'
    | '/konto'
    | '/profil'
    | '/anfragen/$'
    | '/api/health'
    | '/anfragen'
    | '/admin/benutzer'
    | '/admin/freigaben'
    | '/admin/katalog'
    | '/admin/protokoll'
    | '/auftraege/$requestId'
    | '/auftraege/neu'
    | '/api/dateien/$fileId'
    | '/auftraege'
    | '/api/dateien'
    | '/admin/organisationen/$organisationId'
    | '/admin/organisationen/neu'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/login'
    | '/admin/organisationen'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/anmelden'
    | '/login'
    | '/registrieren'
    | '/_app/admin'
    | '/_app/konto'
    | '/_app/profil'
    | '/anfragen/$'
    | '/api/health'
    | '/anfragen/'
    | '/_app/admin/benutzer'
    | '/_app/admin/freigaben'
    | '/_app/admin/katalog'
    | '/_app/admin/protokoll'
    | '/_app/auftraege/$requestId'
    | '/_app/auftraege/neu'
    | '/api/dateien/$fileId'
    | '/_app/auftraege/'
    | '/api/dateien/'
    | '/_app/admin/organisationen/$organisationId'
    | '/_app/admin/organisationen/neu'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/login'
    | '/_app/admin/organisationen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AnmeldenRoute: typeof AnmeldenRoute
  LoginRoute: typeof LoginRoute
  RegistrierenRoute: typeof RegistrierenRoute
  AnfragenSplatRoute: typeof AnfragenSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AnfragenIndexRoute: typeof AnfragenIndexRoute
  ApiDateienFileIdRoute: typeof ApiDateienFileIdRoute
  ApiDateienIndexRoute: typeof ApiDateienIndexRoute
  ApiAuthOidcCallbackRoute: typeof ApiAuthOidcCallbackRoute
  ApiAuthOidcLoginRoute: typeof ApiAuthOidcLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/konto': {
      id: '/_app/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AppKontoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/anfragen/': {
      id: '/anfragen/'
      path: '/anfragen'
      fullPath: '/anfragen/'
      preLoaderRoute: typeof AnfragenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anfragen/$': {
      id: '/anfragen/$'
      path: '/anfragen/$'
      fullPath: '/anfragen/$'
      preLoaderRoute: typeof AnfragenSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/benutzer': {
      id: '/_app/admin/benutzer'
      path: '/benutzer'
      fullPath: '/admin/benutzer'
      preLoaderRoute: typeof AppAdminBenutzerRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/freigaben': {
      id: '/_app/admin/freigaben'
      path: '/freigaben'
      fullPath: '/admin/freigaben'
      preLoaderRoute: typeof AppAdminFreigabenRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/katalog': {
      id: '/_app/admin/katalog'
      path: '/katalog'
      fullPath: '/admin/katalog'
      preLoaderRoute: typeof AppAdminKatalogRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/protokoll': {
      id: '/_app/admin/protokoll'
      path: '/protokoll'
      fullPath: '/admin/protokoll'
      preLoaderRoute: typeof AppAdminProtokollRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/auftraege/': {
      id: '/_app/auftraege/'
      path: '/auftraege'
      fullPath: '/auftraege/'
      preLoaderRoute: typeof AppAuftraegeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auftraege/$requestId': {
      id: '/_app/auftraege/$requestId'
      path: '/auftraege/$requestId'
      fullPath: '/auftraege/$requestId'
      preLoaderRoute: typeof AppAuftraegeRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auftraege/neu': {
      id: '/_app/auftraege/neu'
      path: '/auftraege/neu'
      fullPath: '/auftraege/neu'
      preLoaderRoute: typeof AppAuftraegeNeuRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/dateien/': {
      id: '/api/dateien/'
      path: '/api/dateien'
      fullPath: '/api/dateien/'
      preLoaderRoute: typeof ApiDateienIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dateien/$fileId': {
      id: '/api/dateien/$fileId'
      path: '/api/dateien/$fileId'
      fullPath: '/api/dateien/$fileId'
      preLoaderRoute: typeof ApiDateienFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/organisationen/': {
      id: '/_app/admin/organisationen/'
      path: '/organisationen'
      fullPath: '/admin/organisationen/'
      preLoaderRoute: typeof AppAdminOrganisationenIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/organisationen/$organisationId': {
      id: '/_app/admin/organisationen/$organisationId'
      path: '/organisationen/$organisationId'
      fullPath: '/admin/organisationen/$organisationId'
      preLoaderRoute: typeof AppAdminOrganisationenOrganisationIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/organisationen/neu': {
      id: '/_app/admin/organisationen/neu'
      path: '/organisationen/neu'
      fullPath: '/admin/organisationen/neu'
      preLoaderRoute: typeof AppAdminOrganisationenNeuRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/api/auth/oidc/callback': {
      id: '/api/auth/oidc/callback'
      path: '/api/auth/oidc/callback'
      fullPath: '/api/auth/oidc/callback'
      preLoaderRoute: typeof ApiAuthOidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/oidc/login': {
      id: '/api/auth/oidc/login'
      path: '/api/auth/oidc/login'
      fullPath: '/api/auth/oidc/login'
      preLoaderRoute: typeof ApiAuthOidcLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminBenutzerRoute: typeof AppAdminBenutzerRoute
  AppAdminFreigabenRoute: typeof AppAdminFreigabenRoute
  AppAdminKatalogRoute: typeof AppAdminKatalogRoute
  AppAdminProtokollRoute: typeof AppAdminProtokollRoute
  AppAdminOrganisationenOrganisationIdRoute: typeof AppAdminOrganisationenOrganisationIdRoute
  AppAdminOrganisationenNeuRoute: typeof AppAdminOrganisationenNeuRoute
  AppAdminOrganisationenIndexRoute: typeof AppAdminOrganisationenIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminBenutzerRoute: AppAdminBenutzerRoute,
  AppAdminFreigabenRoute: AppAdminFreigabenRoute,
  AppAdminKatalogRoute: AppAdminKatalogRoute,
  AppAdminProtokollRoute: AppAdminProtokollRoute,
  AppAdminOrganisationenOrganisationIdRoute:
    AppAdminOrganisationenOrganisationIdRoute,
  AppAdminOrganisationenNeuRoute: AppAdminOrganisationenNeuRoute,
  AppAdminOrganisationenIndexRoute: AppAdminOrganisationenIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppKontoRoute: typeof AppKontoRoute
  AppProfilRoute: typeof AppProfilRoute
  AppAuftraegeRequestIdRoute: typeof AppAuftraegeRequestIdRoute
  AppAuftraegeNeuRoute: typeof AppAuftraegeNeuRoute
  AppAuftraegeIndexRoute: typeof AppAuftraegeIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppKontoRoute: AppKontoRoute,
  AppProfilRoute: AppProfilRoute,
  AppAuftraegeRequestIdRoute: AppAuftraegeRequestIdRoute,
  AppAuftraegeNeuRoute: AppAuftraegeNeuRoute,
  AppAuftraegeIndexRoute: AppAuftraegeIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AnmeldenRoute: AnmeldenRoute,
  LoginRoute: LoginRoute,
  RegistrierenRoute: RegistrierenRoute,
  AnfragenSplatRoute: AnfragenSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  AnfragenIndexRoute: AnfragenIndexRoute,
  ApiDateienFileIdRoute: ApiDateienFileIdRoute,
  ApiDateienIndexRoute: ApiDateienIndexRoute,
  ApiAuthOidcCallbackRoute: ApiAuthOidcCallbackRoute,
  ApiAuthOidcLoginRoute: ApiAuthOidcLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
